'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const C=window.K9_CONFIG||{};
const DEFAULT_SETTINGS={id:1,organization_name:C.ORGANIZATION_NAME||'K9 Napoletano Academy',app_name:C.APP_NAME||'K9 Studio Dogsitter',subtitle:'',description:'',address:'',postal_code:'',city:'',province:'',country:'Italia',phone:'',mobile:'',email:'',website:'',vat_number:'',fiscal_code:'',iban:'',social_text:'',footer_text:'',legal_text:'',primary_color:'#0f5f53',secondary_color:'#153e75',header_color:'#ffffff',card_color:'#ffffff',button_color:'#0f5f53',logo_url:'',logo_size:48,logo_position:'sinistra',show_logo_pdf:true,show_header_pdf:true,show_footer_pdf:true,show_fiscal_data_pdf:true,show_qr_pdf:false,show_photos_pdf:false,show_signatures_pdf:false,pdf_attachments:[],attach_pdfs_to_quotes:true};
const state={session:null,profile:null,customers:[],dogs:[],profiles:[],services:[],quotes:[],documents:[],communications:[],communicationReads:[],notifications:[],trash:[],settings:{...DEFAULT_SETTINGS}};
const roleLabels={owner:'Datore di lavoro',vice_admin:'Vice amministratore',dipendente:'Dipendente'};
const statusLabels={programmato:'Programmato',in_corso:'In corso',da_verificare:'Da verificare',chiuso:'Chiuso',annullato:'Annullato'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const dateIT=v=>v?new Date(v+'T12:00:00').toLocaleDateString('it-IT'):'—';
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseLocalDate=value=>{const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||''));if(!match)return null;const date=new Date(Number(match[1]),Number(match[2])-1,Number(match[3]),12,0,0,0);return Number.isNaN(date.getTime())?null:date};
const addDays=(value,days)=>{const date=parseLocalDate(value);if(!date)throw Error('Data non valida.');date.setDate(date.getDate()+Number(days||0));return localDate(date)};
const daysBetween=(from,to)=>{const start=parseLocalDate(from),end=parseLocalDate(to);if(!start||!end)return null;return Math.round((end-start)/86400000)};
const quoteValidityValue=(quoteDate,validUntil)=>{const days=daysBetween(quoteDate,validUntil);return [7,15,30,60,90].includes(days)?String(days):'custom'};
