'use strict';
function applyIdentity(){const x=state.settings||DEFAULT_SETTINGS;document.documentElement.style.setProperty('--p',x.primary_color||DEFAULT_SETTINGS.primary_color);document.documentElement.style.setProperty('--p2',x.secondary_color||DEFAULT_SETTINGS.secondary_color);document.documentElement.style.setProperty('--header',x.header_color||'#ffffff');document.documentElement.style.setProperty('--card',x.card_color||'#ffffff');document.documentElement.style.setProperty('--button',x.button_color||x.primary_color||DEFAULT_SETTINGS.button_color);document.title=x.app_name||DEFAULT_SETTINGS.app_name;const logo=identityLogo();const appLogo=$('#appLogo');if(appLogo){appLogo.src=logo;appLogo.style.width=`${Number(x.logo_size||48)}px`;appLogo.style.height=`${Number(x.logo_size||48)}px`}const loginLogo=$('.auth-card .logo');if(loginLogo)loginLogo.src=logo;const brand=$('#appBrandName');if(brand)brand.textContent=x.app_name||DEFAULT_SETTINGS.app_name;const b=$('.brand');if(b){b.classList.remove('logo-left','logo-center','logo-right');b.classList.add(x.logo_position==='centro'?'logo-center':x.logo_position==='destra'?'logo-right':'logo-left')}}
function settingField(name,label,type='text',wide=false){const v=state.settings[name]??'';const attrs=name==='logo_size'?' min="28" max="160" step="1" inputmode="numeric"':'';return `<label class="${wide?'wide':''}">${label}<input name="${name}" type="${type}" value="${esc(v)}"${attrs}></label>`}
function storageObjectPath(publicUrl,bucket){try{const marker=`/storage/v1/object/public/${bucket}/`;const i=String(publicUrl||'').indexOf(marker);return i>=0?decodeURIComponent(String(publicUrl).slice(i+marker.length)):''}catch{return ''}}
async function removeStorageObject(bucket,path){if(!path)return;const r=await fetch(`${C.SUPABASE_URL}/storage/v1/object/${bucket}/${encodeURI(path)}`,{method:'DELETE',headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${state.session.access_token}`}});if(!r.ok&&r.status!==404){const t=await r.text();throw Error(t||`Impossibile eliminare il file da ${bucket}`)}}
function cleanSettingValue(name,value){const v=String(value??'').trim();if(name==='email')return v.toLowerCase();if(name==='website'&&v&&!/^https?:\/\//i.test(v))return `https://${v}`;return v}
function settingArea(name,label){return `<label class="wide">${label}<textarea name="${name}">${esc(state.settings[name]||'')}</textarea></label>`}
function checkField(name,label){return `<label class="check-row"><input name="${name}" type="checkbox" ${state.settings[name]?'checked':''}><span>${label}</span></label>`}

function pdfAttachments(){let a=state.settings.pdf_attachments;if(typeof a==='string'){try{a=JSON.parse(a)}catch{a=[]}}return Array.isArray(a)?a:[]}
const formatFileSize=bytes=>{const n=Number(bytes||0);if(!n)return 'Dimensione non disponibile';if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`};
function attachmentSettingsBlock(){
  const attachments=pdfAttachments();
  const rows=attachments.map(a=>`<article class="pdf-attachment-card ${a.enabled===false?'is-disabled':''}">
    <div class="pdf-attachment-icon" aria-hidden="true">PDF</div>
    <div class="pdf-attachment-info"><strong title="${esc(a.name)}">${esc(a.name)}</strong><div class="pdf-attachment-meta"><span>${a.enabled===false?'Disattivato':'Attivo'}</span><span>${formatFileSize(a.size)}</span>${a.pages?`<span>${Number(a.pages)} pagine</span>`:''}</div><small>Caricato ${a.created_at?new Date(a.created_at).toLocaleString('it-IT'):'—'}</small></div>
    <div class="pdf-attachment-actions"><button type="button" onclick="previewPdfAttachment('${a.id}')">Anteprima</button><button type="button" onclick="downloadPdfAttachment('${a.id}')">Scarica</button><button type="button" onclick="preparePdfAttachmentReplace('${a.id}')">Sostituisci</button><button type="button" onclick="togglePdfAttachment('${a.id}')">${a.enabled===false?'Attiva':'Disattiva'}</button><button type="button" class="danger" onclick="removePdfAttachment('${a.id}')">Elimina</button></div>
  </article>`).join('')||'<div class="pdf-attachments-empty"><strong>Nessun allegato caricato</strong><span>Carica regolamento, privacy, condizioni o altri documenti da unire al preventivo.</span></div>';
  return `<div class="settings-info-banner"><strong>Allegati automatici al PDF cliente</strong><p>I PDF attivi vengono aggiunti in coda al preventivo cliente. Non vengono inseriti nel PDF interno e non vengono inviati automaticamente.</p><span>${attachments.length} ${attachments.length===1?'allegato':'allegati'} configurati</span></div>
  <div class="pdf-upload-control"><input id="pdfAttachmentFile" class="visually-hidden" type="file" accept="application/pdf"><button type="button" class="primary" onclick="preparePdfAttachmentUpload()">+ Carica PDF</button><span id="pdfAttachmentSelection" class="muted">Nessun file selezionato</span></div>
  <label class="checkbox-line pdf-auto-attach-toggle"><input type="checkbox" name="attach_pdfs_to_quotes" ${state.settings.attach_pdfs_to_quotes!==false?'checked':''}> Allega automaticamente i PDF attivi ai preventivi</label>
  <div class="pdf-attachment-list">${rows}</div>`}
async function saveAttachmentList(list){const rows=await request('/rest/v1/app_settings?id=eq.1',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({pdf_attachments:list})});if(Array.isArray(rows)&&!rows.length)throw Error('Impostazioni allegati non aggiornate');state.settings.pdf_attachments=list}
window.preparePdfAttachmentUpload=()=>{const input=$('#pdfAttachmentFile');if(!input)return;delete input.dataset.replaceId;input.click()};
window.preparePdfAttachmentReplace=id=>{const input=$('#pdfAttachmentFile');if(!input)return;input.dataset.replaceId=id;input.click()};
async function attachmentPageCount(file){try{if(!window.PDFLib?.PDFDocument)return null;const doc=await PDFLib.PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true});return doc.getPageCount()}catch{return null}}
window.uploadPdfAttachment=async e=>{const input=e.target,file=input.files?.[0],replaceId=input.dataset.replaceId||'';if(!file)return;const selection=$('#pdfAttachmentSelection');if(selection)selection.textContent=file.name;if(file.type!=='application/pdf'){input.value='';delete input.dataset.replaceId;return toast('Seleziona un file PDF valido.')}if(file.size>10*1024*1024){input.value='';delete input.dataset.replaceId;return toast('Il PDF supera 10 MB.')}let path='';try{const current=pdfAttachments(),old=replaceId?current.find(x=>x.id===replaceId):null,id=old?.id||crypto.randomUUID(),safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),newPath=`settings/${crypto.randomUUID()}-${safe}`;path=newPath;const r=await fetch(`${C.SUPABASE_URL}/storage/v1/object/pdf-attachments/${newPath}`,{method:'POST',headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${state.session.access_token}`,'Content-Type':'application/pdf','x-upsert':'false'},body:file});const t=await r.text();if(!r.ok)throw Error(t||'Caricamento non riuscito');const pages=await attachmentPageCount(file),entry={id,name:file.name,path:newPath,size:file.size,pages,enabled:old?.enabled!==false,created_at:new Date().toISOString()};const list=old?current.map(x=>x.id===id?entry:x):[...current,entry];try{await saveAttachmentList(list)}catch(err){await removeStorageObject('pdf-attachments',newPath).catch(()=>{});throw err}if(old?.path&&old.path!==newPath)await removeStorageObject('pdf-attachments',old.path).catch(()=>{});renderSettings();toast(old?'PDF sostituito':'PDF allegato salvato')}catch(err){toast(err.message||'Caricamento allegato non riuscito')}finally{input.value='';delete input.dataset.replaceId}};
async function fetchPdfAttachmentBlob(path){const r=await fetch(`${C.SUPABASE_URL}/storage/v1/object/pdf-attachments/${path}`,{headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${state.session.access_token}`}});if(!r.ok)throw Error('Impossibile leggere il PDF allegato.');return await r.blob()}
window.previewPdfAttachment=async id=>{
  const a=pdfAttachments().find(x=>x.id===id);
  if(!a)return toast('Allegato non trovato');
  try{
    const blob=await fetchPdfAttachmentBlob(a.path);
    const fileUrl=URL.createObjectURL(blob);
    const title=esc(a.name||'Allegato PDF');
    const meta=[a.pages?`${Number(a.pages)} ${Number(a.pages)===1?'pagina':'pagine'}`:'',formatFileSize(a.size)].filter(Boolean).join(' · ');
    modal('Anteprima PDF',`<section class="pdf-preview-shell">
      <header class="pdf-preview-header">
        <div class="pdf-preview-file-icon" aria-hidden="true">PDF</div>
        <div class="pdf-preview-file-info"><strong title="${title}">${title}</strong><span>${esc(meta||'Documento PDF')}</span></div>
      </header>
      <div id="pdfPreviewStatus" class="pdf-preview-status">Preparazione anteprima…</div>
      <div id="pdfPreviewPages" class="pdf-preview-pages" aria-live="polite"></div>
      <div class="pdf-preview-fallback hidden" id="pdfPreviewFallback"><p>Il visualizzatore integrato non è disponibile su questo dispositivo.</p><button type="button" class="primary" id="pdfPreviewOpenExternal">Apri il PDF</button></div>
      <footer class="pdf-preview-actions"><button type="button" id="pdfPreviewDownload">Scarica</button><button type="button" class="primary" id="pdfPreviewOpen">Apri a schermo intero</button></footer>
    </section>`,async()=>{});
    const save=$('#modalSave');if(save)save.classList.add('hidden');
    const cancel=$('#modalForm .modal-actions button[value=cancel]');if(cancel)cancel.textContent='Chiudi';
    const openFile=()=>{const w=window.open(fileUrl,'_blank','noopener,noreferrer');if(!w)toast('Consenti l’apertura del PDF nel browser.')};
    $('#pdfPreviewOpen')?.addEventListener('click',openFile);
    $('#pdfPreviewOpenExternal')?.addEventListener('click',openFile);
    $('#pdfPreviewDownload')?.addEventListener('click',()=>{const link=document.createElement('a');link.href=fileUrl;link.download=a.name||'allegato.pdf';document.body.appendChild(link);link.click();link.remove()});
    const status=$('#pdfPreviewStatus'),pagesHost=$('#pdfPreviewPages'),fallback=$('#pdfPreviewFallback');
    try{
      if(!window.pdfjsLib?.getDocument)throw Error('Visualizzatore PDF non caricato');
      window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
      const bytes=new Uint8Array(await blob.arrayBuffer());
      const pdf=await window.pdfjsLib.getDocument({data:bytes}).promise;
      if(status)status.textContent=`${pdf.numPages} ${pdf.numPages===1?'pagina':'pagine'} · scorri per visualizzare`;
      if(pagesHost)pagesHost.innerHTML='';
      for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){
        const page=await pdf.getPage(pageNumber);
        const base=page.getViewport({scale:1});
        const available=Math.min(900,Math.max(280,(pagesHost?.clientWidth||600)-24));
        const scale=Math.min(2,available/base.width);
        const viewport=page.getViewport({scale});
        const wrap=document.createElement('figure');wrap.className='pdf-preview-page';
        const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.setAttribute('aria-label',`Pagina ${pageNumber}`);
        const caption=document.createElement('figcaption');caption.textContent=`Pagina ${pageNumber} di ${pdf.numPages}`;
        wrap.append(canvas,caption);pagesHost?.appendChild(wrap);
        await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport}).promise;
      }
    }catch(renderError){
      console.warn('Anteprima PDF integrata non disponibile:',renderError);
      if(status)status.textContent='Anteprima non disponibile';
      fallback?.classList.remove('hidden');
    }
    const dialog=$('#modal'),cleanup=()=>{URL.revokeObjectURL(fileUrl);dialog.removeEventListener('close',cleanup)};
    dialog.addEventListener('close',cleanup);
  }catch(e){toast(e.message||'Impossibile aprire l’anteprima')}
};
window.downloadPdfAttachment=async id=>{const a=pdfAttachments().find(x=>x.id===id);if(!a)return toast('Allegato non trovato');try{const blob=await fetchPdfAttachmentBlob(a.path),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=a.name||'allegato.pdf';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){toast(e.message)}};
window.togglePdfAttachment=async id=>{try{const list=pdfAttachments().map(a=>a.id===id?{...a,enabled:a.enabled===false}:a);await saveAttachmentList(list);renderSettings();toast('Allegato aggiornato')}catch(e){toast(e.message)}};
window.removePdfAttachment=async id=>{const a=pdfAttachments().find(x=>x.id===id);if(!a||!confirm(`Rimuovere definitivamente ${a.name}?`))return;try{await removeStorageObject('pdf-attachments',a.path);await saveAttachmentList(pdfAttachments().filter(x=>x.id!==id));renderSettings();toast('Allegato rimosso')}catch(e){toast(e.message)}};

function settingsDetails(title,subtitle,content,open=false){return `<details class="settings-accordion" ${open?'open':''}><summary><span><strong>${title}</strong>${subtitle?`<small>${subtitle}</small>`:''}</span><span class="accordion-chevron" aria-hidden="true"></span></summary><div class="settings-block">${content}</div></details>`}
function renderSettings(){if(!isAdmin()){show('dashboard');return}const s=state.settings;
  const logoBlock=`<div class="logo-preview"><img id="settingsLogoPreview" src="${esc(identityLogo())}" alt="Logo attivo"><div><label>Carica nuovo logo<input id="identityLogoFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></label><p class="muted">Formati PNG, JPG, WEBP o SVG. Massimo 5 MB.</p><button type="button" id="restoreDefaultLogo">Ripristina logo predefinito</button></div></div><div class="settings-grid">${settingField('logo_size','Dimensione logo (28-160 px)','number')}<label>Posizione logo<select name="logo_position"><option value="sinistra" ${s.logo_position==='sinistra'?'selected':''}>Sinistra</option><option value="centro" ${s.logo_position==='centro'?'selected':''}>Centro</option><option value="destra" ${s.logo_position==='destra'?'selected':''}>Destra</option></select></label></div>`;
  const identityBlock=`<div class="settings-grid">${settingField('organization_name','Nome attività')}${settingField('app_name','Nome applicazione')}${settingField('subtitle','Sottotitolo','text',true)}${settingArea('description','Descrizione')}${settingField('address','Indirizzo')}${settingField('postal_code','CAP')}${settingField('city','Comune')}${settingField('province','Provincia')}${settingField('country','Nazione')}${settingField('phone','Telefono')}${settingField('mobile','Cellulare')}${settingField('email','Email','email')}${settingField('website','Sito web')}${settingField('vat_number','Partita IVA')}${settingField('fiscal_code','Codice fiscale')}${settingField('iban','IBAN','text',true)}${settingArea('social_text','Social e altri riferimenti')}</div>`;
  const graphicsBlock=`<div class="settings-grid">${settingField('primary_color','Colore principale','color')}${settingField('secondary_color','Colore secondario','color')}${settingField('header_color','Colore intestazione','color')}${settingField('card_color','Colore schede','color')}${settingField('button_color','Colore pulsanti','color')}</div><p class="muted">I colori vengono applicati dopo il salvataggio.</p>`;
  const pdfBlock=`<div class="settings-grid">${settingArea('footer_text','Testo piè di pagina')}${settingArea('legal_text','Note legali / privacy')}${checkField('show_logo_pdf','Mostra logo nel PDF')}${checkField('show_header_pdf','Mostra intestazione nel PDF')}${checkField('show_footer_pdf','Mostra piè di pagina e note legali')}${checkField('show_fiscal_data_pdf','Mostra dati fiscali e contatti nel PDF')}${checkField('show_signatures_pdf','Mostra firme nel PDF')}</div><p class="muted">Il QR e la fotografia sono gestiti dal Pass identificativo e non dai PDF di servizio o preventivo.</p>`;
  $('#settingsPanel').innerHTML=`<form id="identityForm">${settingsDetails('Logo','Caricamento, dimensione e posizione',logoBlock,true)}${settingsDetails('Intestazione e dati attività','Dati usati nell’app e nei PDF',identityBlock)}${settingsDetails('Grafica','Colori dell’interfaccia e dei documenti',graphicsBlock)}${settingsDetails('PDF e piè di pagina','Visibilità, dati attività e testi legali',pdfBlock)}${settingsDetails('Allegati automatici ai preventivi','Regolamento, privacy e condizioni',attachmentSettingsBlock())}<div class="settings-actions"><button id="saveSettingsButton" class="primary" type="submit">Salva impostazioni</button><button type="button" id="resetIdentity">Ripristina identità e grafica</button><button type="button" id="resetPdfSettings">Ripristina impostazioni PDF</button></div></form>`;
  $('#identityForm').onsubmit=saveSettings;$('#identityLogoFile').onchange=previewAndUploadLogo;$('#pdfAttachmentFile').onchange=uploadPdfAttachment;$('#restoreDefaultLogo').onclick=()=>setLogoUrl('');$('#resetIdentity').onclick=resetIdentitySettings;$('#resetPdfSettings').onclick=resetPdfSettings}
async function saveSettings(e){e.preventDefault();const form=e.currentTarget,button=$('#saveSettingsButton'),f=new FormData(form),data={};for(const [k,v] of f.entries())data[k]=cleanSettingValue(k,v);['show_logo_pdf','show_header_pdf','show_footer_pdf','show_fiscal_data_pdf','show_signatures_pdf','attach_pdfs_to_quotes'].forEach(k=>data[k]=f.has(k));data.logo_size=Math.max(28,Math.min(160,Number(data.logo_size||48)));if(!data.organization_name||!data.app_name)return toast('Nome attività e nome applicazione sono obbligatori.');if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))return toast('Inserisci un indirizzo email valido.');try{if(button){button.disabled=true;button.textContent='Salvataggio...'}const rows=await request('/rest/v1/app_settings?id=eq.1',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});if(Array.isArray(rows)&&!rows.length)throw Error('La riga delle impostazioni non è stata aggiornata');state.settings={...state.settings,...data};applyIdentity();toast('Impostazioni salvate')}catch(err){toast(err.message||'Impossibile salvare le impostazioni')}finally{if(button){button.disabled=false;button.textContent='Salva impostazioni'}}}
async function previewAndUploadLogo(e){const file=e.target.files?.[0];if(!file)return;e.target.value='';const allowed=['image/png','image/jpeg','image/webp','image/svg+xml'];if(!allowed.includes(file.type))return toast('Formato logo non valido. Usa PNG, JPG, WEBP o SVG.');if(file.size>5*1024*1024)return toast('Il logo supera 5 MB');const ext=({'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/svg+xml':'svg'})[file.type];const path=`identity/logo-${Date.now()}.${ext}`;try{const r=await fetch(`${C.SUPABASE_URL}/storage/v1/object/app-assets/${path}`,{method:'POST',headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${state.session.access_token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});const t=await r.text();if(!r.ok)throw Error(t||'Caricamento logo non riuscito');const url=`${C.SUPABASE_URL}/storage/v1/object/public/app-assets/${path}`;try{await setLogoUrl(url)}catch(err){await removeStorageObject('app-assets',path).catch(()=>{});throw err}}catch(err){toast(err.message||'Caricamento logo non riuscito')}}
async function setLogoUrl(url){const previous=state.settings.logo_url||'';const rows=await request('/rest/v1/app_settings?id=eq.1',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({logo_url:url})});if(Array.isArray(rows)&&!rows.length)throw Error('Logo non aggiornato');state.settings.logo_url=url;applyIdentity();const p=$('#settingsLogoPreview');if(p)p.src=identityLogo();const oldPath=storageObjectPath(previous,'app-assets');if(oldPath&&previous!==url)await removeStorageObject('app-assets',oldPath).catch(err=>console.warn('Logo precedente non eliminato:',err.message));toast(url?'Logo aggiornato':'Logo predefinito ripristinato')}
async function resetIdentitySettings(){if(!confirm('Ripristinare solo logo, nomi e colori iniziali? Dati fiscali, testi PDF e allegati non verranno modificati.'))return;const keys=['organization_name','app_name','subtitle','description','primary_color','secondary_color','header_color','card_color','button_color','logo_url','logo_size','logo_position'];const data=Object.fromEntries(keys.map(k=>[k,DEFAULT_SETTINGS[k]]));const previous=state.settings.logo_url||'';await request('/rest/v1/app_settings?id=eq.1',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});state.settings={...state.settings,...data};applyIdentity();const oldPath=storageObjectPath(previous,'app-assets');if(oldPath)await removeStorageObject('app-assets',oldPath).catch(()=>{});renderSettings();toast('Identità e grafica ripristinate')}
async function resetPdfSettings(){if(!confirm('Ripristinare solo le opzioni PDF e i testi del piè di pagina? Gli allegati caricati resteranno disponibili.'))return;const keys=['footer_text','legal_text','show_logo_pdf','show_header_pdf','show_footer_pdf','show_fiscal_data_pdf','show_signatures_pdf','attach_pdfs_to_quotes'];const data=Object.fromEntries(keys.map(k=>[k,DEFAULT_SETTINGS[k]]));await request('/rest/v1/app_settings?id=eq.1',{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});state.settings={...state.settings,...data};renderSettings();toast('Impostazioni PDF ripristinate')}

