'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const C=window.K9_CONFIG||{};
const state={session:null,profile:null,customers:[],dogs:[],profiles:[],services:[],documents:[]};
const roleLabels={owner:'Datore di lavoro',vice_admin:'Vice amministratore',dipendente:'Dipendente'};
const statusLabels={programmato:'Programmato',in_corso:'In corso',da_verificare:'Da verificare',chiuso:'Chiuso',annullato:'Annullato'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n||0));
const dateIT=v=>v?new Date(v+'T12:00:00').toLocaleDateString('it-IT'):'—';
const localDate=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)};
const isAdmin=()=>['owner','vice_admin'].includes(state.profile?.role), isOwner=()=>state.profile?.role==='owner', isEmployee=()=>state.profile?.role==='dipendente';
function configured(){return /^https:\/\/.+\.supabase\.co$/.test(C.SUPABASE_URL||'')&&!String(C.SUPABASE_ANON_KEY||'').startsWith('INCOLLA_')}
function authHeaders(extra={}){return {'apikey':C.SUPABASE_ANON_KEY,'Authorization':`Bearer ${state.session?.access_token||C.SUPABASE_ANON_KEY}`,'Content-Type':'application/json',...extra}}
async function refreshSession(){if(!state.session?.refresh_token)throw Error('Sessione scaduta.');const r=await fetch(`${C.SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:C.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:state.session.refresh_token})});const d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||'Sessione scaduta.');state.session=d;localStorage.setItem('k9_session',JSON.stringify(d));return d}
async function request(path,opt={},retry=true){if(!configured())throw Error('Configura config.js prima della pubblicazione.');let r=await fetch(C.SUPABASE_URL+path,{...opt,headers:{...authHeaders(),...(opt.headers||{})}});if(r.status===401&&retry&&state.session?.refresh_token){await refreshSession();return request(path,opt,false)}const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Error(data?.message||data?.error_description||data?.hint||text||`Errore ${r.status}`);return data}
const select=(table,q='select=*')=>request(`/rest/v1/${table}?${q}`);
const insert=(table,data)=>request(`/rest/v1/${table}`,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});
const update=(table,id,data)=>request(`/rest/v1/${table}?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(data)});
const rpc=(name,body={})=>request(`/rest/v1/rpc/${name}`,{method:'POST',body:JSON.stringify(body)});
async function login(email,password){const r=await fetch(`${C.SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:C.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||'Accesso non riuscito');state.session=d;localStorage.setItem('k9_session',JSON.stringify(d));await bootstrap()}
async function logout(){try{await request('/auth/v1/logout',{method:'POST'})}catch{}localStorage.removeItem('k9_session');location.reload()}
async function restore(){try{state.session=JSON.parse(localStorage.getItem('k9_session')||'null')}catch{}if(!state.session)return false;try{if(Date.now()/1000>(state.session.expires_at||0)-60)await refreshSession();await bootstrap();return true}catch(e){localStorage.removeItem('k9_session');return false}}
async function bootstrap(){const p=await select('profiles',`select=*&id=eq.${state.session.user.id}&limit=1`);state.profile=p[0];if(!state.profile||!state.profile.active)throw Error('Account non attivo.');$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');$('#roleLabel').textContent=`${state.profile.full_name||state.profile.email} · ${roleLabels[state.profile.role]||state.profile.role}`;buildNav();await loadAll();show('dashboard')}
function buildNav(){const a=[['dashboard','Dashboard'],['customers','Clienti'],['dogs','Cani'],['employees','Utenti'],['services','Servizi'],['payments','Economia'],['documents','Documenti'],['audit','Log'],['profile','Pass']];const e=[['dashboard','Oggi'],['customers','Clienti assegnati'],['dogs','Cani assegnati'],['services','I miei servizi'],['compensation','Compensi'],['profile','Il mio pass']];$('#nav').innerHTML=(isAdmin()?a:e).map(([id,l])=>`<button data-screen="${id}">${l}</button>`).join('')}
async function loadAll(){if(isAdmin()){[state.customers,state.dogs,state.profiles,state.services,state.documents]=await Promise.all([select('customers','select=*&order=last_name.asc,first_name.asc'),select('dogs','select=*&order=name.asc'),select('profiles','select=*&order=full_name.asc'),select('dogsitter_services','select=*&order=service_date.desc,service_time.asc'),select('dogsitter_documents','select=*&order=created_at.desc')])}else{const d=await rpc('employee_workspace');state.customers=d.customers||[];state.dogs=d.dogs||[];state.services=d.services||[];state.documents=[];state.profiles=[]}}
function show(id){$$('.screen').forEach(e=>e.classList.add('hidden'));$('#'+id).classList.remove('hidden');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));render(id)}
function render(id){({dashboard:renderDashboard,customers:renderCustomers,dogs:renderDogs,employees:renderEmployees,services:renderServices,compensation:renderComp,payments:renderPayments,documents:renderDocs,audit:renderAudit,profile:renderPass}[id]||(()=>{}))()}
const cname=id=>{const c=state.customers.find(x=>x.id===id);return c?`${c.first_name} ${c.last_name}`:'—'}, dname=id=>state.dogs.find(x=>x.id===id)?.name||'—', pname=id=>state.profiles.find(x=>x.id===id)?.full_name||'—';
const matured=s=>['da_verificare','chiuso'].includes(s.status);
function renderDashboard(){const today=localDate(), todays=state.services.filter(s=>s.service_date===today);if(isAdmin()){$('#dashboard').innerHTML=`<h2>Dashboard amministrativa</h2><div class="stats"><div class="stat"><span>Clienti attivi</span><strong>${state.customers.filter(c=>c.status==='attivo').length}</strong></div><div class="stat"><span>Cani</span><strong>${state.dogs.filter(d=>d.active).length}</strong></div><div class="stat"><span>Servizi oggi</span><strong>${todays.length}</strong></div><div class="stat"><span>Da verificare</span><strong>${state.services.filter(s=>s.status==='da_verificare').length}</strong></div><div class="stat"><span>Da incassare</span><strong>${money(state.services.filter(s=>s.customer_payment_status==='da_incassare'&&matured(s)).reduce((a,s)=>a+Number(s.customer_amount),0))}</strong></div><div class="stat"><span>Da liquidare</span><strong>${money(state.services.filter(s=>s.employee_payment_status==='da_liquidare'&&matured(s)).reduce((a,s)=>a+Number(s.employee_compensation),0))}</strong></div></div><h3>Servizi di oggi</h3><div class="grid">${todays.map(serviceCard).join('')||'<div class="card">Nessun servizio oggi.</div>'}</div>`}else{$('#dashboard').innerHTML=`<h2>Il mio lavoro di oggi</h2><div class="stats"><div class="stat"><span>Servizi</span><strong>${todays.length}</strong></div><div class="stat"><span>Uscite</span><strong>${todays.reduce((a,s)=>a+Number(s.daily_visits||1),0)}</strong></div><div class="stat"><span>Compenso maturato</span><strong>${money(todays.filter(matured).reduce((a,s)=>a+Number(s.employee_compensation),0))}</strong></div></div><div class="grid">${todays.map(serviceCard).join('')||'<div class="card">Nessun servizio oggi.</div>'}</div>`}}
function renderCustomers(){$('[data-action="new-customer"]')?.classList.toggle('hidden',!isAdmin());$('#customerList').innerHTML=state.customers.map(c=>`<article class="card"><h3>${esc(c.first_name)} ${esc(c.last_name)}</h3><p>${esc(c.phone||'')}<br>${esc(c.address||'')} ${esc(c.city||'')}</p>${isAdmin()?`<p><b>Assegnato:</b> ${esc(pname(c.assigned_employee_id))}</p><button onclick="openCustomer('${c.id}')">Modifica</button>`:`<p><b>Emergenza:</b> ${esc(c.emergency_contact||'—')}</p><p class="muted">${esc(c.operational_notes||'Nessuna nota operativa')}</p>`}</article>`).join('')||'<div class="card">Nessun cliente.</div>'}
function renderDogs(){$('[data-action="new-dog"]')?.classList.toggle('hidden',!isAdmin());$('#dogList').innerHTML=state.dogs.map(d=>`<article class="card"><h3>${esc(d.name)}</h3><p>${esc(d.breed||'Razza non indicata')} · ${esc(cname(d.customer_id))}</p><p>${esc(d.feeding_notes||'')}</p><p class="muted">${esc(d.behavior_notes||d.routine_notes||'')}</p>${isAdmin()?`<button onclick="openDog('${d.id}')">Modifica</button>`:''}</article>`).join('')||'<div class="card">Nessun cane.</div>'}
function renderEmployees(){$('#employeeList').innerHTML=state.profiles.map(p=>`<article class="card"><h3>${esc(p.full_name||p.email)}</h3><span class="pill">${esc(roleLabels[p.role]||p.role)}</span><p>${esc(p.employee_code||'')} · ${p.active?'Attivo':'Sospeso'}</p>${p.is_owner?'<p><b>Titolare protetto</b></p>':''}<button onclick="openEmployee('${p.id}')">Gestisci</button></article>`).join('')}
function serviceCard(s){const margin=Number(s.customer_amount||0)-Number(s.employee_compensation||0);let actions='';if(isEmployee()){if(s.status==='programmato')actions=`<button class="primary" onclick="startService('${s.id}')">Inizia</button>`;if(s.status==='in_corso')actions=`<button class="primary" onclick="completeService('${s.id}')">Compila e termina</button>`}else{actions=`<button onclick="openService('${s.id}')">Modifica</button>${s.status==='da_verificare'?`<button class="primary" onclick="approveService('${s.id}')">Approva e genera PDF</button>`:''}${s.status==='chiuso'?`<button onclick="markSent('${s.id}')">Segna inviato</button>`:''}`};return `<article class="card"><h3>${esc(dname(s.dog_id))} · ${esc(cname(s.customer_id))}</h3><p>${dateIT(s.service_date)} ${esc(String(s.service_time||'').slice(0,5))} · ${esc(s.service_type)}</p><span class="pill">${esc(statusLabels[s.status]||s.status)}</span><p>${isEmployee()?`<b>Il tuo compenso:</b> ${money(s.employee_compensation)}`:`<b>Cliente:</b> ${money(s.customer_amount)} · <b>Dipendente:</b> ${money(s.employee_compensation)} · <b>Quota attività:</b> ${money(margin)}`}</p>${s.started_at?`<p class="muted">Inizio reale: ${new Date(s.started_at).toLocaleString('it-IT')}${s.completed_at?` · Fine: ${new Date(s.completed_at).toLocaleString('it-IT')}`:''}</p>`:''}${s.report_text?`<p><b>Rapporto:</b> ${esc(s.report_text)}</p>`:''}<div class="service-actions">${actions}</div></article>`}
function renderServices(){$('[data-action="new-service"]')?.classList.toggle('hidden',!isAdmin());const d=$('#serviceDateFilter').value,st=$('#serviceStatusFilter').value;$('#serviceList').innerHTML=state.services.filter(s=>(!d||s.service_date===d)&&(!st||s.status===st)).map(serviceCard).join('')||'<div class="card">Nessun servizio.</div>'}
function periodTotals(filter){const rows=state.services.filter(s=>filter(s)&&matured(s));return {sum:rows.reduce((a,s)=>a+Number(s.employee_compensation),0),visits:rows.reduce((a,s)=>a+Number(s.daily_visits||1),0)}}
function renderComp(){const now=new Date(),today=localDate(now),week=new Date(now);week.setDate(now.getDate()-((now.getDay()+6)%7));const ws=localDate(week),month=today.slice(0,7);const defs=[['Oggi',s=>s.service_date===today],['Settimana',s=>s.service_date>=ws&&s.service_date<=today],['Mese',s=>s.service_date.startsWith(month)]];$('#compCards').innerHTML=defs.map(([l,f])=>{const t=periodTotals(f);return `<div class="stat"><span>${l}</span><strong>${money(t.sum)}</strong><small>${t.visits} uscite</small></div>`}).join('')+`<div class="stat"><span>Da liquidare</span><strong>${money(state.services.filter(s=>matured(s)&&s.employee_payment_status==='da_liquidare').reduce((a,s)=>a+Number(s.employee_compensation),0))}</strong></div>`;$('#compList').innerHTML=state.services.filter(matured).map(serviceCard).join('')}
function renderPayments(){const maturedRows=state.services.filter(matured),income=maturedRows.filter(s=>s.customer_payment_status==='incassato').reduce((a,s)=>a+Number(s.customer_amount),0),toIncome=maturedRows.filter(s=>s.customer_payment_status==='da_incassare').reduce((a,s)=>a+Number(s.customer_amount),0),toPay=maturedRows.filter(s=>s.employee_payment_status==='da_liquidare').reduce((a,s)=>a+Number(s.employee_compensation),0),margin=maturedRows.reduce((a,s)=>a+Number(s.customer_amount)-Number(s.employee_compensation),0);$('#paymentSummary').innerHTML=`<div class="stat"><span>Incassato</span><strong>${money(income)}</strong></div><div class="stat"><span>Da incassare</span><strong>${money(toIncome)}</strong></div><div class="stat"><span>Da liquidare</span><strong>${money(toPay)}</strong></div><div class="stat"><span>Quota attività maturata</span><strong>${money(margin)}</strong></div>`;$('#paymentList').innerHTML=maturedRows.map(s=>`<article class="card"><h3>${esc(cname(s.customer_id))} · ${esc(dname(s.dog_id))}</h3><p>${dateIT(s.service_date)} · Cliente ${money(s.customer_amount)} (${esc(s.customer_payment_status)})</p><p>Dipendente ${money(s.employee_compensation)} (${esc(s.employee_payment_status)})</p><div class="service-actions"><button onclick="setCustomerPaid('${s.id}')">Segna cliente incassato</button><button onclick="setEmployeePaid('${s.id}')">Segna dipendente liquidato</button></div></article>`).join('')||'<div class="card">Nessun movimento maturato.</div>'}
function renderDocs(){$('#documentList').innerHTML=state.documents.map(d=>`<article class="card"><h3>${esc(d.title||d.file_name)}</h3><p>${esc(d.status)} · ${new Date(d.created_at).toLocaleString('it-IT')}</p><div class="service-actions"><button onclick="openDocument('${d.id}')">Apri PDF</button>${d.status!=='inviato'?`<button onclick="markDocumentSent('${d.id}')">Segna inviato</button>`:''}</div></article>`).join('')||'<div class="card">Nessun documento.</div>'}
async function renderAudit(){const rows=await select('audit_log','select=*&order=created_at.desc&limit=250');$('#auditList').innerHTML=rows.map(a=>`<article class="card"><b>${esc(a.action)}</b><p>${new Date(a.created_at).toLocaleString('it-IT')} · ${esc(a.table_name||'')}</p><small>${esc(JSON.stringify(a.details||{}))}</small></article>`).join('')}
function renderPass(){const p=state.profile;$('#passCard').innerHTML=`<div class="pass"><div class="pass-head"><img src="${esc(p.photo_url||'assets/logo.png')}" alt="Foto"><div><small>${esc(C.ORGANIZATION_NAME||'')}</small><h2>${esc(p.full_name||p.email)}</h2><p>${esc(p.qualification||roleLabels[p.role]||p.role)}</p></div></div><p><b>Codice:</b> ${esc(p.employee_code||'—')}</p><p><b>Stato:</b> ${p.active?'ATTIVO':'SOSPESO'}</p><p><b>Validità:</b> ${dateIT(p.pass_expires_at)}</p><div class="qr">K9:${esc(p.id)}:${p.active?'ACTIVE':'SUSPENDED'}</div></div>`}
function modal(title,html,onSave){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal();$('#modalForm').onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return $('#modal').close();try{await onSave(new FormData(e.currentTarget));$('#modal').close();await loadAll();render($$('.screen:not(.hidden)')[0]?.id||'dashboard');toast('Salvato')}catch(err){toast(err.message)}}}
const field=(n,l,v='',type='text',extra='')=>`<label>${l}<input name="${n}" type="${type}" value="${esc(v)}" ${extra}></label>`;
window.openCustomer=id=>{const c=state.customers.find(x=>x.id===id)||{};const em=state.profiles.filter(p=>p.role==='dipendente'&&p.active);modal(id?'Modifica cliente':'Nuovo cliente',`<div class="form-grid">${field('first_name','Nome',c.first_name,'text','required')}${field('last_name','Cognome',c.last_name,'text','required')}${field('phone','Telefono',c.phone)}${field('email','Email',c.email,'email')}${field('address','Indirizzo',c.address)}${field('city','Comune',c.city)}${field('emergency_contact','Contatto emergenza',c.emergency_contact)}<label>Dipendente assegnato<select name="assigned_employee_id"><option value="">Non assegnato</option>${em.map(p=>`<option value="${p.id}" ${p.id===c.assigned_employee_id?'selected':''}>${esc(p.full_name)}</option>`).join('')}</select></label><label class="wide">Note operative<textarea name="operational_notes">${esc(c.operational_notes||'')}</textarea></label></div>`,async f=>{const d=Object.fromEntries(f);d.assigned_employee_id=d.assigned_employee_id||null;id?await update('customers',id,d):await insert('customers',d)})};
window.openDog=id=>{const d=state.dogs.find(x=>x.id===id)||{};modal(id?'Modifica cane':'Nuovo cane',`<div class="form-grid">${field('name','Nome',d.name,'text','required')}<label>Proprietario<select name="customer_id" required>${state.customers.map(c=>`<option value="${c.id}" ${c.id===d.customer_id?'selected':''}>${esc(c.first_name+' '+c.last_name)}</option>`).join('')}</select></label>${field('breed','Razza',d.breed)}${field('microchip','Microchip',d.microchip)}<label class="wide">Alimentazione<textarea name="feeding_notes">${esc(d.feeding_notes||'')}</textarea></label><label class="wide">Farmaci/allergie<textarea name="medical_notes">${esc(d.medical_notes||'')}</textarea></label><label class="wide">Comportamento e routine<textarea name="behavior_notes">${esc(d.behavior_notes||'')}</textarea></label></div>`,async f=>{const x=Object.fromEntries(f);id?await update('dogs',id,x):await insert('dogs',x)})};
window.openService=id=>{const s=state.services.find(x=>x.id===id)||{};const em=state.profiles.filter(p=>p.role==='dipendente'&&p.active);modal(id?'Modifica servizio':'Nuovo servizio',`<div class="form-grid"><label>Cliente<select id="serviceCustomer" name="customer_id" required>${state.customers.map(c=>`<option value="${c.id}" ${c.id===s.customer_id?'selected':''}>${esc(c.first_name+' '+c.last_name)}</option>`).join('')}</select></label><label>Cane<select id="serviceDog" name="dog_id" required></select></label><label>Dipendente<select name="employee_id" required>${em.map(p=>`<option value="${p.id}" ${p.id===(s.employee_id||state.customers.find(c=>c.id===(s.customer_id||state.customers[0]?.id))?.assigned_employee_id)?'selected':''}>${esc(p.full_name)}</option>`).join('')}</select></label>${field('service_type','Tipo servizio',s.service_type||'Passeggiata','text','required')}${field('service_date','Data',s.service_date||localDate(),'date','required')}${field('service_time','Ora',String(s.service_time||'09:00').slice(0,5),'time','required')}${field('planned_duration_minutes','Durata prevista (minuti)',s.planned_duration_minutes||30,'number','min="1" required')}${field('daily_visits','Uscite',s.daily_visits||1,'number','min="1" required')}${field('customer_amount','Importo cliente',s.customer_amount||0,'number','min="0" step="0.01" required')}${field('employee_compensation','Compenso dipendente',s.employee_compensation||0,'number','min="0" step="0.01" required')}<label class="wide">Note operative<textarea name="operational_notes">${esc(s.operational_notes||'')}</textarea></label></div>`,async f=>{const x=Object.fromEntries(f);['planned_duration_minutes','daily_visits','customer_amount','employee_compensation'].forEach(k=>x[k]=Number(x[k]));if(x.employee_compensation>x.customer_amount)throw Error('Il compenso dipendente non può superare l’importo cliente.');id?await update('dogsitter_services',id,x):await insert('dogsitter_services',x)});const cs=$('#serviceCustomer'),ds=$('#serviceDog');const fill=()=>{const dogs=state.dogs.filter(d=>d.customer_id===cs.value);ds.innerHTML=dogs.map(d=>`<option value="${d.id}" ${d.id===s.dog_id?'selected':''}>${esc(d.name)}</option>`).join('')};cs.onchange=fill;fill()};
window.openEmployee=id=>{const p=state.profiles.find(x=>x.id===id);if(!p)return;const ownerLocked=p.is_owner&&!isOwner();modal('Gestisci account',`<div class="form-grid">${field('full_name','Nome completo',p.full_name,'text','required')}${field('employee_code','Codice',p.employee_code)}${field('qualification','Qualifica',p.qualification)}${field('pass_expires_at','Scadenza pass',p.pass_expires_at||'','date')}<label>Ruolo<select name="role" ${ownerLocked?'disabled':''}><option value="dipendente" ${p.role==='dipendente'?'selected':''}>Dipendente</option><option value="vice_admin" ${p.role==='vice_admin'?'selected':''}>Vice amministratore</option>${p.is_owner?'<option value="owner" selected>Datore di lavoro</option>':''}</select></label><label>Stato<select name="active" ${ownerLocked?'disabled':''}><option value="true" ${p.active?'selected':''}>Attivo</option><option value="false" ${!p.active?'selected':''}>Sospeso</option></select></label></div>`,async f=>{const x=Object.fromEntries(f);x.active=x.active==='true';if(p.is_owner&&!isOwner())throw Error('Il titolare può essere modificato solo dal titolare.');await rpc('admin_update_profile',{p_user_id:id,p_full_name:x.full_name,p_employee_code:x.employee_code||null,p_qualification:x.qualification||null,p_pass_expires_at:x.pass_expires_at||null,p_role:x.role||p.role,p_active:x.active})})};
window.startService=async id=>{await rpc('start_my_service',{p_service_id:id});await loadAll();renderServices();toast('Servizio iniziato')};
window.completeService=id=>modal('Concludi servizio',`<div class="form-grid"><label class="wide">Rapporto obbligatorio<textarea name="report" required></textarea></label><label class="wide">Anomalie o note<textarea name="incident"></textarea></label></div>`,async f=>rpc('complete_my_service',{p_service_id:id,p_report_text:f.get('report'),p_incident_notes:f.get('incident')||null}));
function pdfEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function wrapText(text,max=82){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){if(line)lines.push(line);line=w}else line=(line+' '+w).trim()}if(line)lines.push(line);return lines}
function makeSimplePdf(data){const lines=[C.ORGANIZATION_NAME||'K9 Studio Dogsitter','RAPPORTO UFFICIALE DI SERVIZIO','',`Documento: ${data.document_number}`,`Cliente: ${data.customer_name}`,`Cane: ${data.dog_name}`,`Dipendente: ${data.employee_name}`,`Data: ${dateIT(data.service_date)}  Ora prevista: ${String(data.service_time||'').slice(0,5)}`,`Inizio reale: ${data.started_at?new Date(data.started_at).toLocaleString('it-IT'):'-'}`,`Fine reale: ${data.completed_at?new Date(data.completed_at).toLocaleString('it-IT'):'-'}`,`Tipo servizio: ${data.service_type}`,`Uscite: ${data.daily_visits}`,'','Rapporto:',...wrapText(data.report_text),...(data.incident_notes?['','Anomalie / note:',...wrapText(data.incident_notes)]:[]),'',`Approvato da: ${data.approver_name}`,`Data approvazione: ${new Date(data.approved_at).toLocaleString('it-IT')}`];let y=790,content='BT\n/F1 11 Tf\n';for(const l of lines){if(y<55)break;content+=`1 0 0 1 50 ${y} Tm (${pdfEscape(l)}) Tj\n`;y-=17}content+='ET';const objs=[];objs[1]='<< /Type /Catalog /Pages 2 0 R >>';objs[2]='<< /Type /Pages /Kids [3 0 R] /Count 1 >>';objs[3]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>';objs[4]=`<< /Length ${content.length} >>\nstream\n${content}\nendstream`;objs[5]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';let pdf='%PDF-1.4\n',offsets=[0];for(let i=1;i<=5;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n';for(let i=1;i<=5;i++)pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
async function uploadDocument(path,blob){const r=await fetch(`${C.SUPABASE_URL}/storage/v1/object/service-documents/${path}`,{method:'POST',headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${state.session.access_token}`,'Content-Type':'application/pdf','x-upsert':'true'},body:blob});const t=await r.text();if(!r.ok)throw Error(t||'Caricamento PDF non riuscito')}
window.approveService=async id=>{if(!confirm('Approvare il rapporto e generare il PDF ufficiale?'))return;const data=await rpc('approve_service',{p_service_id:id});const blob=makeSimplePdf(data);await uploadDocument(data.storage_path,blob);await rpc('finalize_document',{p_document_id:data.document_id});await loadAll();renderServices();toast('Rapporto approvato e PDF archiviato')};
window.setCustomerPaid=async id=>{await rpc('set_customer_payment',{p_service_id:id,p_status:'incassato'});await loadAll();renderPayments();toast('Incasso registrato')};
window.setEmployeePaid=async id=>{await rpc('set_employee_payment',{p_service_id:id,p_status:'liquidato'});await loadAll();renderPayments();toast('Liquidazione registrata')};
window.openDocument=async id=>{const d=await rpc('get_document_path',{p_document_id:id});const r=await request(`/storage/v1/object/sign/service-documents/${d.path}`,{method:'POST',body:JSON.stringify({expiresIn:600})});window.open(C.SUPABASE_URL+'/storage/v1'+r.signedURL,'_blank','noopener')};
window.markDocumentSent=async id=>{const ch=prompt('Canale di invio: WhatsApp, email o altro','WhatsApp');if(!ch)return;await rpc('mark_document_sent',{p_document_id:id,p_channel:ch});await loadAll();renderDocs();toast('Invio registrato')};
window.markSent=async sid=>{const d=state.documents.find(x=>x.service_id===sid);if(d)return markDocumentSent(d.id);toast('Documento non trovato')};
async function createAccount(){modal('Nuovo account',`<div class="form-grid">${field('email','Email','','email','required')}${field('password','Password temporanea','','password','minlength="8" required')}${field('full_name','Nome completo','','text','required')}${field('employee_code','Codice dipendente')}<label>Ruolo<select name="role"><option value="dipendente">Dipendente</option>${isOwner()?'<option value="vice_admin">Vice amministratore</option>':''}</select></label></div>`,async f=>{const body=Object.fromEntries(f);const r=await request('/functions/v1/create-user',{method:'POST',body:JSON.stringify(body)});toast(r.message||'Account creato')})}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#authError').textContent='';try{if(!configured())throw Error('Configura config.js.');await login($('#loginEmail').value.trim(),$('#loginPassword').value)}catch(err){$('#authError').textContent=err.message}});
$('#forgotPassword').onclick=async()=>{try{const email=$('#loginEmail').value.trim();if(!email)throw Error('Inserisci prima l’email.');await request('/auth/v1/recover',{method:'POST',body:JSON.stringify({email})});toast('Email di recupero inviata')}catch(e){toast(e.message)}};
$('#logoutBtn').onclick=logout;$('#nav').onclick=e=>{const b=e.target.closest('[data-screen]');if(b)show(b.dataset.screen)};
$('[data-action="new-customer"]').onclick=()=>openCustomer();$('[data-action="new-dog"]').onclick=()=>openDog();$('[data-action="new-service"]').onclick=()=>openService();$('[data-action="new-employee"]').onclick=createAccount;
$('#serviceDateFilter').onchange=renderServices;$('#serviceStatusFilter').onchange=renderServices;$('#clearFilters').onclick=()=>{$('#serviceDateFilter').value='';$('#serviceStatusFilter').value='';renderServices()};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
restore();
